### ISSUE TITLE
Invalid ATOM feed links

### ISSUE THREAD

**Issue by palb91** [Animeshz/site#1]
I found something wrong on this page:

  https://animeshz.github.io/site/atom.xml

Here's what it is:

  The links generated do not match the urls of the site. Example with your last blog post:

URL:

    https://animeshz.github.io/site/blogs/void-linux.html

ATOM:

```xml
<link href="https://animeshz.github.io/site/site//home/runner/work/site/site/content/blogs/void-linux.html"/>
```

I really enjoy reading you, keep up with the interesting stuff! ;)

**Comment by palb91** [comment]
You may also consider adding the body of the page in the ATOM feeds, this way people could keep the comfort of their RSS reader.

**Comment by Animeshz** [comment]
Ah, thanks for informing!

Will quickly push a fix as soon as possible.

**Comment by Animeshz** [comment]
Link issue is fixed, I'll try adding the body, I don't think vitepress exposes the content part of html separately, so I'd have to look about that.
