### ISSUE TITLE
Update vitepress

### ISSUE THREAD

**Issue by Animeshz** [Animeshz/site#11]
[Vitepress](https://vitepress.dev/) is the framework used behind this website, it offers a wide range of Vue components to be used along with markdown-based pages.

This is a good-first-issue for people that can work with npm & javascript in general, to update that package to the latest version, and ensuring that nothing breaks (testing it locally).

To work on this issue please comment for the assignment as this issue can only be solved once.

**Comment by pritamgupta-07** [comment]
Hey! can you assign this issue to me

**Comment by Animeshz** [comment]
Sure, go ahead!

**Comment by Animeshz** [comment]
Closed by #16.
