### ISSUE TITLE
Rename the next blog discussions by Gitalk to have a prefix on the issue.

### ISSUE THREAD

**Issue by Animeshz** [Animeshz/site#13]
Currently the blog comments are handled by [Gitalk](https://github.com/gitalk/gitalk), a modern comment component based on Github Issue and Preact.

This makes it possible to include a live comment system in a static-site that can be hosted in the https://github.io, but the problem arises when the issue section is bombarded with comment posts. This issue wants to name the new issues to have a prefix such as `[COMMENT] <name of the blog-post>` instead of just `<name of the blog-post>`.

Find the vue component that handles this, and perform the required changes. Be sure to test the changes locally, making sure everything works as expected.

To work on this issue please comment for the assignment as this issue can only be solved once.

**Comment by Zwnow** [comment]
Hey man, I would love to try this one!

**Comment by Animeshz** [comment]
Go ahead!

**Comment by Zwnow** [comment]
Thank you!
I got a quick question though. I never used Gitalk. The issue seems very doable and I am pretty sure I already solved it, but I don't know how to test the Gitalk functionality. Do I have to follow through the Gitalk documentation and create my own Github Application to test on or is there a better way?

**Comment by Animeshz** [comment]
If you're unsure about it, just send the PR I'll test it on my own.

Happy Hacking 😃 !

**Comment by Zwnow** [comment]
Just did it, thanks! 🚀

**Comment by Animeshz** [comment]
Closed by #15
